import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import Navbar from "./Navbar/page"
import './globals.css'
import Link from 'next/link'
import {Menu} from 'lucide-react';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle,SheetTrigger,} from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/toaster"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar/> */}

        {/* Header */}
        <header className='flex justify-between py-6 px-4 bg-gray-100 items-center'>

          {/* Left Side */}
          <div>
            <h1 className='text-3xl font-bold text-gray-900'>XYZ</h1>
          </div>

          {/* Right Side */}
          <nav>
            <ul className='text-lg font-medium md:flex hidden gap-x-8 '>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/">About</Link>
              </li>
              <li>
                <Link href="/">Contact</Link>
              </li>
              <li>
                <Link href="/">Blogs</Link>
              </li>
            </ul>
            <div className='md:hidden flex'>
              <Sheet>
                <SheetTrigger><Menu /></SheetTrigger>
                <SheetContent>
                  <SheetHeader>
                    <SheetTitle>Are you sure absolutely sure?</SheetTitle>
                    <SheetDescription>
                      This action cannot be undone. This will permanently delete your account
                      and remove your data from our servers.0000000000
                    </SheetDescription>
                  </SheetHeader>
                </SheetContent>
              </Sheet>
            </div>
          </nav>
        </header>
        {children}
        <Toaster/>
      </body>
    </html>
  )
}
