var a = 15;
console.log("Is a == 15 | I predict true");
console.log(a == 15);
var b = "Hello";
console.log("Is b == 'Hello' | I predict true");
console.log(b === "Hello");
var c = 1.5;
console.log("Is c == 1.5 | I predict true");
console.log(c == 1.5);
var d = false;
console.log("Is d == false | I predict true");
console.log(d == false);
var e = -2.6;
console.log("Is e == -2.6 | I predict true");
console.log(e == -2.6);
var f = 14;
console.log("Is f == 15 | I predict false");
console.log(f == 15);
var g = "Heelo";
console.log("Is g == 'Hello' | I predict false");
console.log(g === "Hello");
var h = 1.6;
console.log("Is h == 1.5 | I predict false");
console.log(h == 1.5);
var i = 'abc';
console.log("Is i == 'xyz' | I predict false");
console.log(i === 'xyz');
var j = -2.7;
console.log("Is j == -2.6 | I predict false");
console.log(j == -2.6);
